"""empty message

Revision ID: 968fe68d7b7a
Revises: 7b492f68be32
Create Date: 2018-03-11 18:22:59.215000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968fe68d7b7a'
down_revision = '7b492f68be32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('account_type', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_table', 'account_type')
    # ### end Alembic commands ###
