"""empty message

Revision ID: e92a0bf3ba18
Revises: 59c604cf6a5d
Create Date: 2018-03-11 20:12:44.927000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92a0bf3ba18'
down_revision = '59c604cf6a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_table', sa.Column('salt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_table', 'salt')
    # ### end Alembic commands ###
