"""empty message

Revision ID: f8578717147a
Revises: 
Create Date: 2018-03-16 19:56:52.198127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8578717147a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('computer_devices',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('model_no', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('service_tag', sa.String(length=80), nullable=True),
    sa.Column('os_type', sa.Integer(), nullable=True),
    sa.Column('keyboard_id', sa.String(length=80), nullable=True),
    sa.Column('monitor_id', sa.String(length=80), nullable=True),
    sa.Column('mouse_id', sa.String(length=80), nullable=True),
    sa.Column('product_key', sa.String(length=80), nullable=True),
    sa.Column('uwi_tag', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyboard_id'),
    sa.UniqueConstraint('monitor_id'),
    sa.UniqueConstraint('mouse_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('product_key'),
    sa.UniqueConstraint('service_tag'),
    sa.UniqueConstraint('uwi_tag')
    )
    op.create_table('device_problems',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('device_id', sa.String(length=80), nullable=True),
    sa.Column('problem', sa.String(length=255), nullable=True),
    sa.Column('logged_by', sa.String(length=80), nullable=True),
    sa.Column('attendee', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id'),
    sa.UniqueConstraint('problem')
    )
    op.create_table('maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=80), nullable=True),
    sa.Column('attendee_id', sa.String(length=80), nullable=True),
    sa.Column('maintained', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('profile_photo', sa.String(length=80), nullable=True),
    sa.Column('account_type', sa.String(length=80), nullable=True),
    sa.Column('salt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_table')
    op.drop_table('maintenance')
    op.drop_table('device_problems')
    op.drop_table('computer_devices')
    # ### end Alembic commands ###
